config/routes.rb
Rails.application.routes.draw do

  get 'online_lending/register'

  get 'online_lending/login'

  post 'session' => 'sessions#create'

  post 'online_lending/lender' => 'online_lending#create_lender'

  get 'online_lending/lender/:id' => 'online_lending#lender', :as => 'lender'

  post 'online_lending/lend_money/:id' => 'online_lending#lend_money', :as => 'lend_money'

  post 'online_lending/borrower' => 'online_lending#create_borrower'

  get 'online_lending/borrower/:id' => 'online_lending#borrower', :as => 'borrower'

  get 'sessions/destroy'

end

app/models/borrower.rb
class Borrower < ActiveRecord::Base
	has_many :histories

	email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

	validates :first_name, :last_name, presence: :true, length: { within: 2..25 }
	validates :email, presence: true, format: { with: email_regex }, uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: { minimum: 6 }
	validates :money, presence: true, numericality: { greater_than_or_equal_to: 1 }
	validates :purpose, presence: true, length: { minimum: 10 }
	validates :description, presence: true, length: { minimum: 15 }

  	def has_password?(submitted_password)
   		self.password == submitted_password
  	end

  	def self.authenticate(email, submitted_password)
	    user = find_by_email(email)
	    return nil if user.nil?
	    return user if user.has_password?(submitted_password)
  	end
end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :lender
  belongs_to :borrower
end

app/models/lender.rb
class Lender < ActiveRecord::Base
	has_many :histories

	email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

	validates :first_name, :last_name, presence: :true, length: { within: 2..25 }
	validates :email, presence: true, format: { with: email_regex }, uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: { minimum: 6 }
	validates :money, presence: true, numericality: { greater_than_or_equal_to: 5 }

	def has_password?(submitted_password)
		self.password == submitted_password
	end

	def self.authenticate(email, submitted_password)
		user = find_by_email(email)
		return nil if user.nil?
		return user if user.has_password?(submitted_password)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/online_lending_controller.rb
class OnlineLendingController < ApplicationController
  def register
  	@lender = Lender.new
  	@borrower = Borrower.new
  	@lender_errors = flash[:lender_errors]
  	@borrower_errors = flash[:borrower_errors]
  end

  def create_lender
  	@lender = Lender.create(lender_params)
  	if @lender.save
  		session[:user_id] = @lender.id
  		session[:user_type] = 'lender'
  		redirect_to lender_path @lender
  	else
  		flash[:lender_errors] = @lender.errors.full_messages
  		redirect_to online_lending_register_path
  	end
  end

    def create_borrower
  	@borrower = Borrower.create(borrower_params)
  	if @borrower.save
  		session[:user_id] = @borrower.id
  		session[:user_type] = 'borrower'
  		redirect_to borrower_path @borrower
  	else
  		flash[:borrower_errors] = @borrower.errors.full_messages
  		redirect_to online_lending_register_path
  	end
  end

  def login
  	@message = flash[:message]
  	@error = flash[:login_error]
  end

  def lender
  	if session[:user_type] == 'lender'
	  	@lender = Lender.find(params[:id])
	  	@borrowers = Borrower.all
	  	@history = History.new
	  	@lendees = History.joins(:borrower).select('*').where(lender:Lender.find(params[:id]))
	else 
		redirect_to online_lending_login_path
	end
  end

  def borrower
  	if session[:user_type] == 'borrower'
  		@borrower = Borrower.find(params[:id])
  		@lenders = History.joins(:lender).select('*').where(borrower:Borrower.find(params[:id]))
  	else 
  		redirect_to online_lending_login_path
  	end
  end

  def lend_money
  	if session[:user_type] != 'lender'
  		redirect_to online_lending_login_path
  	end
  	@lender = Lender.find(session[:user_id])
  	@lender.update(money:@lender.money-params[:amount].to_i)
  	@borrower = Borrower.find(params[:id])
  	if @borrower.raised.nil?
  		@borrower.update(raised:params[:amount].to_i)
  	else
  		@borrower.update(raised:@borrower.raised + params[:amount].to_i)
  	end
  	@history = History.create(amount:params[:amount].to_i, lender:@lender, borrower:@borrower)
  	json_message = {first_name:@borrower.first_name, last_name:@borrower.last_name, purpose:@borrower.purpose, description:@borrower.description, money:@borrower.money, raised:@borrower.raised, amount:@history.amount}
  	render json: json_message
  end

  private
  def lender_params
    params.require(:lender).permit(:first_name, :last_name, :email, :password, :money)
  end

  def borrower_params
    params.require(:borrower).permit(:first_name, :last_name, :email, :password, :money, :purpose, :description, :raised)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	user = Lender.authenticate(params[:session][:email], params[:session][:password])
  	if user.nil?
  		user = Borrower.authenticate(params[:session][:email], params[:session][:password])
  		if user.nil?
  			flash[:login_error] = "Could not find a user with that email and password combination"
  			redirect_to online_lending_login_path
  		else
  			session[:user_type] = 'borrower'
  			session[:user_id] = user.id
  			redirect_to borrower_path user
  		end
  	else
  		session[:user_type] = 'lender'
  		session[:user_id] = user.id
  		redirect_to lender_path user
  	end
  end

  def destroy
  	session[:user_id] = nil
  	session[:user_type] = nil
  	flash[:message] = 'You have successfully logged out'
  	redirect_to online_lending_login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/online_lending_helper.rb
module OnlineLendingHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= yield :title %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
  		<%= yield %>
  	</div>
</body>
</html>

app/views/online_lending/borrower.html.erb
<%= content_for :title do %>
	<title>Borrower Page</title>
<% end %>

<p>Name : <%= @borrower.first_name %> <%= @borrower.last_name %></p>
<p>Amount Needed: $ <%= @borrower.money %></p>
<p>Amount Raised: $ 
	<% if @borrower.raised %>
		<%= @borrower.raised %>
	<% else %>
		0
	<% end %>
</p>

<%= link_to 'Logout', sessions_destroy_path %>

<h2>List of people who lent you money:</h2>
<table class="table table-stripped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th>Amount Lent</th>
		</tr>
	</thead>
	<tbody>
	<% if @lenders %>
		<% @lenders.each do |lender| %>
		<tr>
			<td><%= lender.first_name %> <%= lender.last_name %></td>
			<td><%= lender.email %></td>
			<td>$ <%= lender.amount %></td>
		</tr>
		<% end %>
	<% end %>
	</tbody>
</table>

app/views/online_lending/lender.html.erb
<%= content_for :title do %>
	<title>Lender Page</title>
<% end %>

<p>Name : <%= @lender.first_name %> <%= @lender.last_name %></p>
<p>Account Balance: $ <%= @lender.money %></p>

<%= link_to 'Logout', sessions_destroy_path %>

<h2>List of people in need of help:</h2>
<table class="table table-stripped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Need Money For</th>
			<th>Reason for Loan</th>
			<th>Amount Needed</th>
			<th>Amount Raised</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	<% if @borrowers %>
		<% @borrowers.each do |borrower| %>
		<tr>
			<td><%= borrower.first_name %> <%= borrower.last_name %></td>
			<td><%= borrower.purpose %></td>
			<td><%= borrower.description %></td>
			<td>$ <%= borrower.money %></td>
			<td>$
				<% if borrower.raised %>
					<%= borrower.raised %>
				<% else %>
					0
				<% end %>
			</td>
			<td>
			<% if @lender.money > 0 %>
				<form class="lend" action="<%= lend_money_path borrower.id %>" method="post">
					<% @money = nil %>
					<% if borrower.raised.nil? %>
						<% borrower.raised = 0 %>
					<% end %>
					<% if @lender.money > borrower.money - borrower.raised %>
						<% @money = borrower.money - borrower.raised %>
					<% else %>
						<% @money = @lender.money %>
					<% end %>
					<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
					<input type="number" name="amount" min="1" max="<%= @money %>">
					<input type="submit" value="Lend">
				</form>
			<% end %>
			</td> 
		</tr>
		<% end %>
	<% end %>
	</tbody>
</table>

<h2>List of people you have lent money to:</h2>
<table class="table table-stripped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Need Money For</th>
			<th>Reason for Loan</th>
			<th>Amount Needed</th>
			<th>Amount Raised</th>
			<th>Amount Lent</th>
		</tr>
	</thead>
	<tbody class="borrowers">
	<% if @lendees %>
		<% @lendees.each do |lend| %>
		<tr>
			<td><%= lend.first_name %> <%= lend.last_name %></td>
			<td><%= lend.purpose %></td>
			<td><%= lend.description %></td>
			<td>$ <%= lend.money %></td>
			<td>$ <%= lend.raised %></td>
			<td>$ <%= lend.amount %></td>
		</tr>
		<% end %>
	<% end %>
	</tbody>
</table>

app/views/online_lending/login.html.erb
<%= content_for :title do %>
	<title>Login Page</title>
<% end %>

<h1>Login</h1>
<% if @message %>
	<p><%= @message %></p>
<% elsif @error %>
	<div class="alert alert-danger"><%= @error %></div>
<% end %>
<%= simple_form_for(:session, url: session_path) do |f| %>
	<%= f.input :email %>
	<%= f.input :password %>
	<%= f.button :submit, 'Login', class: "btn btn-primary" %>
<% end %>
<%= link_to 'Click here to register', online_lending_register_path %>

app/views/online_lending/register.html.erb
<%= content_for :title do %>
	<title>Registration Page</title>
<% end %>

<div class="row">
	<div class="col-md-6">
		<h1>Lender</h1>
		<% if @lender_errors %>
			<% @lender_errors.each do |error| %>
				<div class="alert-danger"><%= error %></div>
			<% end %>
		<% end %>
		<%= simple_form_for @lender, url: online_lending_lender_path do |f| %>
			<%= f.input :first_name, required: false, placeholder: "First Name" %>
			<%= f.input :last_name, required: false, placeholder: "Last Name" %>
			<%= f.input :email, required: false, placeholder: "Email" %>
			<%= f.input :password, required: false %>
			<%= f.input :money, required: false %>
			<%= f.button :submit, 'Register', class: "btn btn-primary" %>
		<% end %>
		<%= link_to 'Already a Member?', online_lending_login_path %>
	</div>

	<div class="col-md-6">
		<h1>Borrower</h1>
		<% if @borrower_errors %>
			<% @borrower_errors.each do |error| %>
				<div class="alert-danger"><%= error %></div>
			<% end %>
		<% end %>
		<%= simple_form_for @borrower, url: online_lending_borrower_path do |f| %>
			<%= f.input :first_name, required: false %>
			<%= f.input :last_name, required: false %>
			<%= f.input :email, required: false %>
			<%= f.input :password, required: false %>
			<%= f.input :purpose, required: false, label: 'Need Money For' %>
			<%= f.input :description, required: false %>
			<%= f.input :money, required: false, label: 'Amount Needed' %>
			<%= f.button :submit, 'Register', class: "btn btn-primary" %>
		<% end %>
		<%= link_to 'Already a Member?', online_lending_login_path %>
	</div>
</div>